[package]
name = "elz"
version = "0.1.0"
authors = ["dannypsnl <dannypsnl@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
quick-protobuf = "0.6.2"
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "llvm8-0" }
